server:
  address: 127.0.0.1
  servlet:
    session:
      tracking-modes: cookie
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:file:${java.io.tmpdir}/tecleadBackendChallenge;DB_CLOSE_ON_EXIT=TRUE;
    username: sa
    password: 
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 128KB
      max-request-size: 128KB
  jackson:
    serialization:
      write-dates-as-timestamps: false

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 9000